# Project Name:   INFT 1207 - Lab 5
# Authors:        Hezekiah Cua and Muntadher Al-bawi
# Date:           March 2025
# Description:    Testing magento website with Selenium IDE


# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


# Initialize Firefox
class TestTest2():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}

# Close the browser after the test
  def teardown_method(self, method):
    self.driver.quit()

# Filtering the products
  def test_test2(self):
    self.driver.get("https://magento.softwaretestingboard.com/women/tops-women/hoodies-and-sweatshirts-women.html")
    self.driver.set_window_size(1447, 999)

    # Hovering and clicking the filter options to choose
    element = self.driver.find_element(By.CSS_SELECTOR, ".filter-options-item:nth-child(1) > .filter-options-title")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.XPATH, "//div[@id=\'narrow-by-list\']/div/div").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'narrow-by-list\']/div/div[2]/ol/li[3]/a").click()
    element = self.driver.find_element(By.XPATH, "//div[@id=\'narrow-by-list\']/div/div")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.XPATH, "//div[@id=\'narrow-by-list\']/div/div").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'narrow-by-list\']/div/div[2]/div/div/a[3]/div").click()
    element = self.driver.find_element(By.XPATH, "//div[@id=\'narrow-by-list\']/div[2]/div")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.XPATH, "//div[@id=\'narrow-by-list\']/div[2]/div").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'narrow-by-list\']/div[2]/div[2]/div/div/a[4]/div").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'narrow-by-list\']/div[8]/div").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'narrow-by-list\']/div[8]").click()
    self.driver.find_element(By.XPATH, "//div[@id=\'narrow-by-list\']/div[8]/div[2]/ol/li[2]/a/span").click()
  
