# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest13():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test13(self):
    self.driver.get("https://magento.softwaretestingboard.com/")
    self.driver.set_window_size(1936, 1048)
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.XPATH, "//span[normalize-space()=\'Women\']")))
    element = self.driver.find_element(By.XPATH, "//span[normalize-space()=\'Women\']")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.XPATH, "//a[@id=\'ui-id-9\']//span[contains(text(),\'Tops\')]")))
    element = self.driver.find_element(By.XPATH, "//a[@id=\'ui-id-9\']//span[contains(text(),\'Tops\')]")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.XPATH, "//a[@id=\'ui-id-12\']//span[contains(text(),\'Hoodies & Sweatshirts\')]")))
    self.driver.find_element(By.XPATH, "//a[@id=\'ui-id-12\']//span[contains(text(),\'Hoodies & Sweatshirts\')]").click()
  
