# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


# Launch Firefox to start the test
class TestTest3():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}

# Closes the Firefox once the test is done
  def teardown_method(self, method):
    self.driver.quit()

 # The method that adds the product to the shopping cart
  def test_test3(self):
    self.driver.get("https://magento.softwaretestingboard.com/women/tops-women/hoodies-and-sweatshirts-women.html?color=57&material=38&size=168&style_general=136#")
    self.driver.set_window_size(1936, 1048)

    # Hover the product image
    element = self.driver.find_element(By.CSS_SELECTOR, ".product > .product-image-container .product-image-photo")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()

    # Wait for the add to cart button to appear once the image is hovered
    WebDriverWait(self.driver, 10).until(expected_conditions.visibility_of_element_located((By.XPATH, "(//button[@type=\'submit\'])[2]")))

    # Locate the add to cart button then hover
    element = self.driver.find_element(By.CSS_SELECTOR, ".tocart")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()

    # Click the add to cart button
    self.driver.find_element(By.XPATH, "(//button[@type=\'submit\'])[2]").click()

    # Wait for the shopping cart link to appear then click
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.LINK_TEXT, "shopping cart")))
    self.driver.find_element(By.LINK_TEXT, "shopping cart").click()

    # Wait for the proceed to checkout button to appear then click
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.XPATH, "(//button[@type=\'button\'])[3]")))
    self.driver.find_element(By.CSS_SELECTOR, ".item > .primary").click()
  
