#  Project Name:    ICE5
#  Author:          Hezekiah Cua
#  Date:            March 2025
#  Description:     In-class activity about using Selenium IDE for demo site


# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestGURU99Register():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()

# Test function for the Registration page

  def test_gURU99Register(self):
    self.driver.get("https://demo.guru99.com/test/newtours/register.php")
    self.driver.set_window_size(895, 695)
    self.driver.find_element(By.NAME, "firstName").click()
    self.driver.find_element(By.NAME, "firstName").send_keys("Test")
    self.driver.find_element(By.NAME, "lastName").send_keys("Test")
    self.driver.find_element(By.NAME, "phone").send_keys("1234567890")
    self.driver.find_element(By.ID, "userName").send_keys("test@test.com")
    self.driver.find_element(By.NAME, "address1").send_keys("test")
    self.driver.find_element(By.NAME, "city").send_keys("test")
    self.driver.find_element(By.NAME, "state").send_keys("test")
    self.driver.find_element(By.NAME, "postalCode").click()
    self.driver.find_element(By.NAME, "postalCode").click()
    self.driver.find_element(By.NAME, "postalCode").send_keys("L1BT5N")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("test0089")
    self.driver.find_element(By.NAME, "password").send_keys("123456")
    self.driver.find_element(By.NAME, "confirmPassword").send_keys("123456")
    self.driver.find_element(By.NAME, "submit").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(3) b").text == "Note: Your user name is test0089."

# Test function for the Login

  def test_gURU99LoginB(self):
    self.driver.get("https://demo.guru99.com/test/newtours/index.php")
    self.driver.set_window_size(1133, 816)
    self.driver.find_element(By.NAME, "userName").click()
    self.driver.find_element(By.NAME, "userName").send_keys("test0089")
    self.driver.find_element(By.NAME, "password").send_keys("123456")
    self.driver.find_element(By.NAME, "submit").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "h3").text == "Login Successfully"
  
